# Generated by Django 4.0 on 2021-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('secondname', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
    ]
